### PR TITLE
Updated libmdbx to v0.9.3

### PR DESCRIPTION
**Pull request by vorot93**

### CODE REVIEW

**Review by Kerollmops — COMMENTED** [review]
Seems nice, have you tested this branch in your projects, already?

**Comment by Kerollmops** [comment]
I tried to `cargo test` your branch and there are some errors related to escaped characters.

<details>
  <summary>cargo test output</summary>

```
    Finished test [unoptimized + debuginfo] target(s) in 0.01s
     Running target/debug/deps/mdbx_sys-c1b7deebf6e61e40

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests mdbx_sys

running 1 test
test src/bindings.rs - mdbx_txn_begin_ex (line 1893) ... FAILED

failures:

---- src/bindings.rs - mdbx_txn_begin_ex (line 1893) stdout ----
error: unknown start of token: \
 --> src/bindings.rs:1894:3
  |
3 | - \ref MDBX_TXN_TRY  Do not block when starting
  |   ^

error: unknown start of token: \
 --> src/bindings.rs:1897:20
  |
6 |                  - \ref MDBX_SAFE_NOSYNC, \ref MDBX_NOMETASYNC.
  |                    ^

error: unknown start of token: \
 --> src/bindings.rs:1897:43
  |
6 |                  - \ref MDBX_SAFE_NOSYNC, \ref MDBX_NOMETASYNC.
  |                                           ^

error: unknown start of token: \
 --> src/bindings.rs:1899:23
  |
8 |                    to \ref MDBX_NOMETASYNC or \ref MDBX_SAFE_NOSYNC
  |                       ^

error: unknown start of token: \
 --> src/bindings.rs:1899:47
  |
8 |                    to \ref MDBX_NOMETASYNC or \ref MDBX_SAFE_NOSYNC
  |                                               ^

error: unknown start of token: \
 --> src/bindings.rs:1900:33
  |
9 |                    description. \see sync_modes
  |                                 ^

error: expected expression, found keyword `ref`
 --> src/bindings.rs:1894:4
  |
3 | - \ref MDBX_TXN_TRY  Do not block when starting
  |    ^^^ expected expression

error: aborting due to 7 previous errors

Couldn't compile the test.

failures:
    src/bindings.rs - mdbx_txn_begin_ex (line 1893)

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--doc'
```

</details>

**Comment by vorot93** [comment]
We have zero control over mdbx' docs, we should disable `#![deny(warnings)]` instead.

**Comment by Kerollmops** [comment]
Ok, could you add this, please?

**Comment by vorot93** [comment]
I have disabled doc comments and regenerated with newer bindgen

**Pull request closed without merging**
